version: '3'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
  postgres:
    restart: always
    image: postgres
    expose:
      - "5432"
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    ports:
      - "8000"
    depends_on:
      - postgres
    links:
      - redis
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    ports:
      - "8000"
